#!/bin/sh /etc/rc.common
# Copyright (c) 2011-2015 OpenWrt.org

START=99

separator() {
	echo -e "\033[36m─────────────────────────────────────────────\033[0m"
}

success='\e[46;30m[SUCCESS]\e[0m'
warn='\e[41;37m[WARN]\e[0m'
info='\e[42;30m[INFO]\e[0m'

start() {
	separator
	pgrep -f /root/node-bot-wrt/index.js > /dev/null
	if [ $? -eq 0 ]; then
		echo -e "$warn ⚠️ bot already running, stopping first..."
		kill $(pgrep -f /root/node-bot-wrt/index.js) >/dev/null 2>&1
		sleep 2
	fi
	cd /root/node-bot-wrt && node /root/node-bot-wrt/index.js >/dev/null 2>&1 &
	echo -e "$info 🚀 starting bot..."
	node-bot -cb >/dev/null 2>&1
	separator
	return 0
}

stop() {
	separator
	echo -e "$info stopping bot..."
	sleep 2
	kill $(pgrep -f /root/node-bot-wrt/index.js) >/dev/null 2>&1
	echo -e "$success bot stopped"
	node-bot -rcb >/dev/null 2>&1
	separator
}

restart(){
	stop
	sleep 2
	start
}

boot() {
	separator
	echo -e "$info ⏳ booting bot (waiting 10 sec)..."
	sleep 10
	/root/node-bot-wrt/lib/bot/booting.sh >/dev/null
	(start >/dev/null 2>&1) &
	echo -e "$success ✨ bot boot completed!"
	separator
	return 0
}